Feature: terminal object model inference
  As a test author recording a session
  I want inference to read the screen and name what it sees
  So that the generated plan addresses roles and names instead of coordinates

  Rule: inference enriches the terminal object model at capture time only. The deterministic model is the spine; the inference engine is a second producer of the same shape, so a plan authored by hand needs no model at all.

  Scenario: an unavailable engine leaves the deterministic model standing
    Given inference is unavailable
    And a virtual screen showing a bordered pane titled "Files" listing "src" and "tests"
    When the terminal object model is inferred
    Then the region named "Files" has the role "list"

  Scenario: inference names a region the deterministic pass left unnamed
    Given a virtual screen whose top line reads "  Files   Settings   Quit  "
    And an engine that labels that line a "menu"
    When the terminal object model is inferred
    Then the model contains a region with the role "menu"

  Scenario: an engine result that violates the model schema is discarded
    Given a virtual screen showing a bordered pane titled "Files" listing "src" and "tests"
    And an engine that returns a region with the role "wormhole"
    When the terminal object model is inferred
    Then the region named "Files" has the role "list"

  @inference
  Scenario: the configured engine infers a conforming model from a real screen
    Given the fixture terminal program is captured through a PTY
    When the terminal object model is inferred by the configured engine
    Then it conforms to the "tom" schema in "scantlings/tom.schema.json"

  @inference
  Scenario: the configured engine generates an acronym expansion
    When an acronym expansion is generated by the configured engine
    Then a non-empty expansion is produced
